server:
  port: 8083

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud?characterEncoding=UTF-8
    username: root
    password: root
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8858
feign:
  sentinel:
    enabled: true

seata:
  service:

    vgroup-mapping:
      # 这里需要对事务组做映射，默认的分组名为 应用名称-seata-service-group，将其映射到default集群
      # 这个很关键，一定要配置对，不然会找不到服务
      user-service-seata-service-group: default_tx_group
    grouplist:
      default: localhost:7091